name: publish
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steos:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t omnia156/justice-league-python-app:v1.0
      - name: publish
        run: |
          docker push omnia156/justice-league-python-app:v1.0