name: publish
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t omnia156/justice-league-python-app:v1.0
      - name: publish
        run: |
          docker login -u omnia156 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push omnia156/justice-league-python-app:v1.0
